<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\V1\TaskController;
use App\Http\Controllers\Api\V1\ProjectController;
use App\Http\Controllers\Api\V1\ProjectDashboardController;
use App\Http\Controllers\Api\V1\ProjectTaskController;
use App\Http\Controllers\Api\V1\ProjectMilestoneController;
use App\Http\Controllers\Api\V1\ProjectStatusUpdateController;
use App\Http\Controllers\Api\V1\ProjectProgressController;
use App\Http\Controllers\Api\V1\ProductivityDashboardController;
use App\Http\Controllers\Api\V1\ProductivityHabitController;
use App\Http\Controllers\Api\V1\ProductivityGoalController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\LifeBalanceController;
use App\Http\Controllers\Api\FinanceAccountController;
use App\Http\Controllers\Api\FinanceTransactionController;
use App\Http\Controllers\Api\HealthNutritionLogController;
use App\Http\Controllers\Api\V1\HealthAlertController;
use App\Http\Controllers\Api\V1\HealthReportController;
use App\Http\Controllers\Api\V1\NutritionFoodController;
use App\Http\Controllers\Api\V1\NutritionCustomFoodController;

use App\Http\Controllers\Api\V1\Dashboard\DashboardController;
use App\Http\Controllers\Api\V1\Finance\FinanceBudgetController;

use App\Http\Controllers\Api\V1\Health\HealthDashboardController;
use App\Http\Controllers\Api\V1\Health\HealthLabTestController;
use App\Http\Controllers\Api\V1\Health\MedicationController;
use App\Http\Controllers\Api\V1\Health\MedicationReminderController;
use App\Http\Controllers\Api\V1\Health\MedicationDoseController;
use App\Http\Controllers\Api\V1\Health\SleepLogController;
use App\Http\Controllers\Api\V1\Health\HealthStepLogController;
use App\Http\Controllers\Api\V1\Health\HealthMoodLogController;

use App\Http\Controllers\Api\V1\HealthWeightLogController;
use App\Http\Controllers\Api\V1\HealthHydrationLogController;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Main API prefix generated by Laravel: /api
| Version prefix in this file: /v1
| Final API prefix: /api/v1
|
*/

/*
|--------------------------------------------------------------------------
| Public API Health Check
|--------------------------------------------------------------------------
*/

Route::get('/health', function () {
    return response()->json([
        'success' => true,
        'message' => 'Nix Life OS API is running.',
        'timestamp' => now()->toISOString(),
    ]);
});

/*
|--------------------------------------------------------------------------
| API Version 1
|--------------------------------------------------------------------------
*/

Route::prefix('v1')->group(function () {

    /*
    |--------------------------------------------------------------------------
    | Public Route Loading Test
    |--------------------------------------------------------------------------
    */

    Route::get('/sleep-route-test', function () {
        return response()->json([
            'success' => true,
            'message' => 'API v1 route file is loading correctly.',
        ]);
    });

    /*
    |--------------------------------------------------------------------------
    | Public Auth Routes
    |--------------------------------------------------------------------------
    */

    Route::prefix('auth')->group(function () {
        Route::post('/login', [AuthController::class, 'login']);
        Route::post('/register', [AuthController::class, 'register']);

        Route::middleware('auth:sanctum')->group(function () {
            Route::get('/me', [AuthController::class, 'me']);
            Route::post('/logout', [AuthController::class, 'logout']);
        });
    });

    /*
    |--------------------------------------------------------------------------
    | Protected Routes
    |--------------------------------------------------------------------------
    */

    Route::middleware('auth:sanctum')->group(function () {
        /*
        |--------------------------------------------------------------------------
        | Tasks Module
        |--------------------------------------------------------------------------
        */

        Route::prefix('tasks')->group(function () {
            Route::get('/', [TaskController::class, 'index']);
            Route::post('/', [TaskController::class, 'store']);
            Route::get('/{task}', [TaskController::class, 'show']);
            Route::put('/{task}', [TaskController::class, 'update']);
            Route::patch('/{task}', [TaskController::class, 'update']);
            Route::delete('/{task}', [TaskController::class, 'destroy']);

            Route::patch('/{task}/complete', [TaskController::class, 'complete']);
            Route::patch('/{task}/reopen', [TaskController::class, 'reopen']);
        });
        /*
        |--------------------------------------------------------------------------
        | Authenticated User
        |--------------------------------------------------------------------------
        */
/*
|--------------------------------------------------------------------------
| Projects Module
|--------------------------------------------------------------------------
*/

        Route::prefix('projects')->group(function () {
            Route::get('/dashboard', [ProjectDashboardController::class, 'summary']);

            Route::get('/', [ProjectController::class, 'index']);
            Route::post('/', [ProjectController::class, 'store']);
            Route::get('/{project}', [ProjectController::class, 'show']);
            Route::put('/{project}', [ProjectController::class, 'update']);
            Route::patch('/{project}', [ProjectController::class, 'update']);
            Route::delete('/{project}', [ProjectController::class, 'destroy']);

            Route::get('/{project}/progress', [ProjectProgressController::class, 'show']);
            Route::post('/{project}/progress/recalculate', [ProjectProgressController::class, 'recalculate']);
            Route::get('/{project}/tasks', [ProjectTaskController::class, 'index']);
            Route::post('/{project}/tasks', [ProjectTaskController::class, 'store']);

            /*
            |--------------------------------------------------------------------------
            | Task Progress Update
            |--------------------------------------------------------------------------
            | Keep this route before /tasks/{task} update routes.
            */
            Route::patch('/{project}/tasks/{task}/progress', [ProjectProgressController::class, 'updateTaskProgress']);
            Route::put('/{project}/tasks/{task}/progress', [ProjectProgressController::class, 'updateTaskProgress']);

            Route::get('/{project}/tasks/{task}', [ProjectTaskController::class, 'show']);
            Route::put('/{project}/tasks/{task}', [ProjectTaskController::class, 'update']);
            Route::patch('/{project}/tasks/{task}', [ProjectTaskController::class, 'update']);
            Route::delete('/{project}/tasks/{task}', [ProjectTaskController::class, 'destroy']);

            Route::get('/{project}/milestones', [ProjectMilestoneController::class, 'index']);
            Route::post('/{project}/milestones', [ProjectMilestoneController::class, 'store']);
            Route::put('/{project}/milestones/{milestone}', [ProjectMilestoneController::class, 'update']);
            Route::patch('/{project}/milestones/{milestone}', [ProjectMilestoneController::class, 'update']);
            Route::delete('/{project}/milestones/{milestone}', [ProjectMilestoneController::class, 'destroy']);

            Route::get('/{project}/status-updates', [ProjectStatusUpdateController::class, 'index']);
            Route::post('/{project}/status-updates', [ProjectStatusUpdateController::class, 'store']);
        });
        Route::get('/user', function (Request $request) {
            return response()->json([
                'success' => true,
                'message' => 'Authenticated user loaded successfully.',
                'data' => $request->user(),
            ]);
        });

        /*
        |--------------------------------------------------------------------------
        | Dashboard
        |--------------------------------------------------------------------------
        */

        Route::get('/dashboard/summary', [DashboardController::class, 'summary']);

        /*
        |--------------------------------------------------------------------------
        | Productivity Module
        |--------------------------------------------------------------------------
        */

        Route::prefix('productivity')->group(function () {
            Route::get('/calendar/events', [ProductivityCalendarEventController::class, 'index']);
            Route::post('/calendar/events', [ProductivityCalendarEventController::class, 'store']);
            Route::get('/calendar/events/{event}', [ProductivityCalendarEventController::class, 'show']);
            Route::put('/calendar/events/{event}', [ProductivityCalendarEventController::class, 'update']);
            Route::delete('/calendar/events/{event}', [ProductivityCalendarEventController::class, 'destroy']);
      
            Route::get('/dashboard', [ProductivityDashboardController::class, 'summary']);
            Route::get('/goals', [ProductivityGoalController::class, 'index']);
            Route::post('/goals', [ProductivityGoalController::class, 'store']);
            Route::get('/goals/{goal}', [ProductivityGoalController::class, 'show']);
            Route::put('/goals/{goal}', [ProductivityGoalController::class, 'update']);
            Route::patch('/goals/{goal}', [ProductivityGoalController::class, 'update']);
            Route::delete('/goals/{goal}', [ProductivityGoalController::class, 'destroy']);

            Route::patch('/goals/{goal}/progress', [ProductivityGoalController::class, 'updateProgress']);
            Route::patch('/goals/{goal}/complete', [ProductivityGoalController::class, 'complete']);
            Route::patch('/goals/{goal}/reopen', [ProductivityGoalController::class, 'reopen']);
            Route::post('/goals/{goal}/recalculate-progress', [ProductivityGoalController::class, 'recalculateProgress']);

            Route::post('/goals/{goal}/tasks', [ProductivityGoalController::class, 'linkTask']);
            Route::delete('/goals/{goal}/tasks/{taskId}', [ProductivityGoalController::class, 'unlinkTask']);

            Route::post('/goals/{goal}/habits', [ProductivityGoalController::class, 'linkHabit']);
            Route::delete('/goals/{goal}/habits/{habitId}', [ProductivityGoalController::class, 'unlinkHabit']);
            Route::get('/habits', [ProductivityHabitController::class, 'index']);
            Route::post('/habits', [ProductivityHabitController::class, 'store']);
            Route::get('/habits/summary/weekly', [ProductivityHabitController::class, 'weeklySummary']);
            Route::get('/habits/{habit}', [ProductivityHabitController::class, 'show']);
            Route::put('/habits/{habit}', [ProductivityHabitController::class, 'update']);
            Route::patch('/habits/{habit}', [ProductivityHabitController::class, 'update']);
            Route::delete('/habits/{habit}', [ProductivityHabitController::class, 'destroy']);
            Route::post('/habits/{habit}/check-in', [ProductivityHabitController::class, 'checkIn']);
        });

        /*
        |--------------------------------------------------------------------------
        | Life Balance
        |--------------------------------------------------------------------------
        */

        Route::get('/life-balance/summary', [LifeBalanceController::class, 'summary']);

        /*
        |--------------------------------------------------------------------------
        | Finance Module
        |--------------------------------------------------------------------------
        */

        Route::prefix('finance')->group(function () {
            Route::get('/accounts', [FinanceAccountController::class, 'index']);
            Route::post('/accounts', [FinanceAccountController::class, 'store']);
            Route::get('/accounts/{id}', [FinanceAccountController::class, 'show']);
            Route::put('/accounts/{id}', [FinanceAccountController::class, 'update']);
            Route::patch('/accounts/{id}', [FinanceAccountController::class, 'update']);
            Route::delete('/accounts/{id}', [FinanceAccountController::class, 'destroy']);

            Route::get('/transactions', [FinanceTransactionController::class, 'index']);
            Route::post('/transactions', [FinanceTransactionController::class, 'store']);
            Route::get('/transactions/{id}', [FinanceTransactionController::class, 'show']);
            Route::put('/transactions/{id}', [FinanceTransactionController::class, 'update']);
            Route::patch('/transactions/{id}', [FinanceTransactionController::class, 'update']);
            Route::delete('/transactions/{id}', [FinanceTransactionController::class, 'destroy']);

            Route::get('/budgets', [FinanceBudgetController::class, 'index']);
            Route::post('/budgets', [FinanceBudgetController::class, 'store']);
            Route::get('/budgets/{id}', [FinanceBudgetController::class, 'show']);
            Route::put('/budgets/{id}', [FinanceBudgetController::class, 'update']);
            Route::patch('/budgets/{id}', [FinanceBudgetController::class, 'update']);
            Route::delete('/budgets/{id}', [FinanceBudgetController::class, 'destroy']);
        });

        /*
        |--------------------------------------------------------------------------
        | Nutrition Facts Database Module
        |--------------------------------------------------------------------------
        */

        Route::prefix('nutrition')->group(function () {
            Route::get('/categories', [NutritionFoodController::class, 'categories']);

            Route::get('/foods/search', [NutritionFoodController::class, 'search']);
            Route::get('/foods/{id}/servings', [NutritionFoodController::class, 'servings']);
            Route::get('/foods/{id}', [NutritionFoodController::class, 'show']);
            Route::get('/foods', [NutritionFoodController::class, 'index']);
            Route::post('/foods/autofill', [NutritionFoodController::class, 'autofill']);

            Route::get('/custom-foods', [NutritionCustomFoodController::class, 'index']);
            Route::post('/custom-foods', [NutritionCustomFoodController::class, 'store']);
            Route::get('/custom-foods/{id}', [NutritionCustomFoodController::class, 'show']);
            Route::put('/custom-foods/{id}', [NutritionCustomFoodController::class, 'update']);
            Route::patch('/custom-foods/{id}', [NutritionCustomFoodController::class, 'update']);
            Route::delete('/custom-foods/{id}', [NutritionCustomFoodController::class, 'destroy']);
        });

        /*
        |--------------------------------------------------------------------------
        | Health Module
        |--------------------------------------------------------------------------
        */

        Route::prefix('health')->group(function () {

            Route::get('/reports/daily', [HealthReportController::class, 'daily']);
            Route::get('/reports/weekly', [HealthReportController::class, 'weekly']);
            Route::get('/reports/monthly', [HealthReportController::class, 'monthly']);
            Route::get('/reports/export-preview', [HealthReportController::class, 'exportPreview']);
            Route::get('/alerts', [HealthAlertController::class, 'index']);
            Route::get('/alerts/summary', [HealthAlertController::class, 'summary']);
            Route::post('/alerts/run', [HealthAlertController::class, 'run']);

            Route::patch('/alerts/{id}/read', [HealthAlertController::class, 'markAsRead']);
            Route::patch('/alerts/{id}/resolve', [HealthAlertController::class, 'resolve']);
            Route::patch('/alerts/{id}/dismiss', [HealthAlertController::class, 'dismiss']);

            Route::delete('/alerts/{id}', [HealthAlertController::class, 'destroy']);
            /*
            |--------------------------------------------------------------------------
            | Health Dashboard
            |--------------------------------------------------------------------------
            */

            Route::get('/dashboard', [HealthDashboardController::class, 'summary']);

            /*
            |--------------------------------------------------------------------------
            | Medication Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/medications', [MedicationController::class, 'index']);
            Route::post('/medications', [MedicationController::class, 'store']);
            Route::get('/medications/{id}', [MedicationController::class, 'show']);
            Route::put('/medications/{id}', [MedicationController::class, 'update']);
            Route::patch('/medications/{id}', [MedicationController::class, 'update']);
            Route::delete('/medications/{id}', [MedicationController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Medication Reminders
            |--------------------------------------------------------------------------
            */

            Route::get('/medication-reminders', [MedicationReminderController::class, 'index']);
            Route::get('/medication-reminders/today', [MedicationReminderController::class, 'today']);
            Route::post('/medication-reminders', [MedicationReminderController::class, 'store']);
            Route::put('/medication-reminders/{id}', [MedicationReminderController::class, 'update']);
            Route::patch('/medication-reminders/{id}', [MedicationReminderController::class, 'update']);
            Route::delete('/medication-reminders/{id}', [MedicationReminderController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Medication Dose Logs
            |--------------------------------------------------------------------------
            */

            Route::get('/medication-doses/history', [MedicationDoseController::class, 'history']);
            Route::post('/medication-doses/{id}/taken', [MedicationDoseController::class, 'markTaken']);
            Route::post('/medication-doses/{id}/skipped', [MedicationDoseController::class, 'markSkipped']);

            /*
            |--------------------------------------------------------------------------
            | Lab Test Results Tracking
            |--------------------------------------------------------------------------
            |
            | Important:
            | categories and trends must stay above /lab-tests/{id}
            | to prevent Laravel from treating "categories" or "trends" as an ID.
            |
            */

            Route::get('/lab-tests/categories', [HealthLabTestController::class, 'categories']);
            Route::get('/lab-tests/trends', [HealthLabTestController::class, 'trends']);
            Route::get('/lab-tests', [HealthLabTestController::class, 'index']);
            Route::post('/lab-tests', [HealthLabTestController::class, 'store']);
            Route::get('/lab-tests/{id}', [HealthLabTestController::class, 'show']);
            Route::put('/lab-tests/{id}', [HealthLabTestController::class, 'update']);
            Route::patch('/lab-tests/{id}', [HealthLabTestController::class, 'update']);
            Route::delete('/lab-tests/{id}', [HealthLabTestController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Mood Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/mood', [HealthMoodLogController::class, 'index']);
            Route::post('/mood', [HealthMoodLogController::class, 'store']);
            Route::get('/mood/{id}', [HealthMoodLogController::class, 'show']);
            Route::put('/mood/{id}', [HealthMoodLogController::class, 'update']);
            Route::patch('/mood/{id}', [HealthMoodLogController::class, 'update']);
            Route::delete('/mood/{id}', [HealthMoodLogController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Sleep Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/sleep', [SleepLogController::class, 'index']);
            Route::post('/sleep', [SleepLogController::class, 'store']);
            Route::get('/sleep/{id}', [SleepLogController::class, 'show']);
            Route::put('/sleep/{id}', [SleepLogController::class, 'update']);
            Route::patch('/sleep/{id}', [SleepLogController::class, 'update']);
            Route::delete('/sleep/{id}', [SleepLogController::class, 'destroy']);

            Route::get('/sleep-test', function () {
                return response()->json([
                    'success' => true,
                    'message' => 'Sleep test route works.',
                ]);
            });

            /*
            |--------------------------------------------------------------------------
            | Steps Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/steps', [HealthStepLogController::class, 'index']);
            Route::post('/steps', [HealthStepLogController::class, 'store']);
            Route::get('/steps/summary', [HealthStepLogController::class, 'summary']);
            Route::get('/steps/{id}', [HealthStepLogController::class, 'show']);
            Route::put('/steps/{id}', [HealthStepLogController::class, 'update']);
            Route::patch('/steps/{id}', [HealthStepLogController::class, 'update']);
            Route::delete('/steps/{id}', [HealthStepLogController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Weight Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/weight', [HealthWeightLogController::class, 'index']);
            Route::post('/weight', [HealthWeightLogController::class, 'store']);
            Route::get('/weight/summary', [HealthWeightLogController::class, 'summary']);
            Route::get('/weight/{id}', [HealthWeightLogController::class, 'show']);
            Route::put('/weight/{id}', [HealthWeightLogController::class, 'update']);
            Route::patch('/weight/{id}', [HealthWeightLogController::class, 'update']);
            Route::delete('/weight/{id}', [HealthWeightLogController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Nutrition Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/nutrition/summary', [HealthNutritionLogController::class, 'summary']);
            Route::get('/nutrition', [HealthNutritionLogController::class, 'index']);
            Route::post('/nutrition', [HealthNutritionLogController::class, 'store']);
            Route::get('/nutrition/{id}', [HealthNutritionLogController::class, 'show']);
            Route::put('/nutrition/{id}', [HealthNutritionLogController::class, 'update']);
            Route::patch('/nutrition/{id}', [HealthNutritionLogController::class, 'update']);
            Route::delete('/nutrition/{id}', [HealthNutritionLogController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Hydration Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/hydration', [HealthHydrationLogController::class, 'index']);
            Route::post('/hydration', [HealthHydrationLogController::class, 'store']);
            Route::get('/hydration/summary/daily', [HealthHydrationLogController::class, 'dailySummary']);
            Route::get('/hydration/summary/weekly', [HealthHydrationLogController::class, 'weeklySummary']);
            Route::post('/hydration/quick-add', [HealthHydrationLogController::class, 'quickAdd']);
            Route::get('/hydration/{id}', [HealthHydrationLogController::class, 'show']);
            Route::put('/hydration/{id}', [HealthHydrationLogController::class, 'update']);
            Route::patch('/hydration/{id}', [HealthHydrationLogController::class, 'update']);
            Route::delete('/hydration/{id}', [HealthHydrationLogController::class, 'destroy']);
        });

        /*
        |--------------------------------------------------------------------------
        | Projects Module
        |--------------------------------------------------------------------------
        |
        | Temporarily disabled because project controllers are missing.
        |
        */

        /*
        Route::prefix('projects')->group(function () {
            Route::get('/dashboard', [ProjectDashboardController::class, 'summary']);
            Route::get('/tasks', [ProjectTaskController::class, 'index']);
            Route::post('/tasks', [ProjectTaskController::class, 'store']);
            Route::get('/tasks/{id}', [ProjectTaskController::class, 'show']);
            Route::put('/tasks/{id}', [ProjectTaskController::class, 'update']);
            Route::patch('/tasks/{id}', [ProjectTaskController::class, 'update']);
            Route::delete('/tasks/{id}', [ProjectTaskController::class, 'destroy']);
        });
        */

        /*
        |--------------------------------------------------------------------------
        | Notifications Module
        |--------------------------------------------------------------------------
        |
        | Temporarily disabled because NotificationController does not exist.
        |
        */

        /*
        Route::prefix('notifications')->group(function () {
            Route::get('/', [NotificationController::class, 'index']);
            Route::post('/', [NotificationController::class, 'store']);
            Route::patch('/read-all', [NotificationController::class, 'markAllAsRead']);
            Route::get('/{id}', [NotificationController::class, 'show']);
            Route::patch('/{id}/read', [NotificationController::class, 'markAsRead']);
            Route::delete('/{id}', [NotificationController::class, 'destroy']);
        });

        Route::prefix('notification-settings')->group(function () {
            Route::get('/', [NotificationSettingController::class, 'index']);
            Route::put('/', [NotificationSettingController::class, 'update']);
            Route::patch('/', [NotificationSettingController::class, 'update']);
        });
        */

        /*
        |--------------------------------------------------------------------------
        | Monitoring Module
        |--------------------------------------------------------------------------
        |
        | Temporarily disabled because MonitoringController may not exist.
        |
        */

        /*
        Route::prefix('monitoring')->group(function () {
            Route::get('/summary', [MonitoringController::class, 'summary']);
            Route::get('/logs', [MonitoringController::class, 'logs']);
            Route::get('/errors', [MonitoringController::class, 'errors']);
            Route::get('/audit-logs', [MonitoringController::class, 'auditLogs']);
        });
        */
    });
});