CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS nix_life_os;
CREATE SCHEMA IF NOT EXISTS finance;
CREATE SCHEMA IF NOT EXISTS health;
CREATE SCHEMA IF NOT EXISTS projects;
CREATE SCHEMA IF NOT EXISTS monitoring;
CREATE SCHEMA IF NOT EXISTS automation;
CREATE SCHEMA IF NOT EXISTS ai;

GRANT ALL PRIVILEGES ON SCHEMA nix_life_os TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA finance TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA health TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA projects TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA monitoring TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA automation TO CURRENT_USER;
GRANT ALL PRIVILEGES ON SCHEMA ai TO CURRENT_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA nix_life_os GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA health GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA projects GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA monitoring GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA automation GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA ai GRANT ALL ON TABLES TO CURRENT_USER;
