#!/usr/bin/env bash

set -e

PROJECT_ROOT="/u01/nix-life-os"
EXPORT_NAME="step76-empty-data-regression-files"
EXPORT_DIR="/tmp/${EXPORT_NAME}"
ARCHIVE_PATH="${PROJECT_ROOT}/${EXPORT_NAME}.tar.gz"

echo "=================================================="
echo " STEP 76 — Empty Data Regression Export"
echo " Project Root: ${PROJECT_ROOT}"
echo " Export Dir:   ${EXPORT_DIR}"
echo " Archive:      ${ARCHIVE_PATH}"
echo "=================================================="

rm -rf "${EXPORT_DIR}"
mkdir -p "${EXPORT_DIR}"

cd "${PROJECT_ROOT}"

copy_if_exists() {
  local path="$1"

  if [ -e "$path" ]; then
    mkdir -p "${EXPORT_DIR}/$(dirname "$path")"
    cp -r "$path" "${EXPORT_DIR}/$path"
    echo "[OK] $path"
  else
    echo "[SKIP] $path"
  fi
}

echo ""
echo "Exporting backend routes..."
copy_if_exists "backend/routes/api.php"

echo ""
echo "Exporting backend controllers..."
copy_if_exists "backend/app/Http/Controllers/Api/V1/DashboardController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/FinanceDashboardController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/FinanceAccountController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/FinanceTransactionController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/FinanceBudgetController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/HealthDashboardController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/HealthNutritionController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/HealthHydrationController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/HealthWeightController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/HealthStepController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/HealthLabTestController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/HealthMedicationController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/ProjectDashboardController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/ProjectController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/ProjectTaskController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/ProductivityDashboardController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/ProductivityTaskController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/ProductivityHabitController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/ProductivityGoalController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/ProductivityCalendarController.php"
copy_if_exists "backend/app/Http/Controllers/Api/V1/AIRecommendationController.php"

echo ""
echo "Exporting backend models..."
copy_if_exists "backend/app/Models/User.php"
copy_if_exists "backend/app/Models/FinanceAccount.php"
copy_if_exists "backend/app/Models/FinanceTransaction.php"
copy_if_exists "backend/app/Models/FinanceBudget.php"
copy_if_exists "backend/app/Models/HealthNutritionLog.php"
copy_if_exists "backend/app/Models/HealthHydrationLog.php"
copy_if_exists "backend/app/Models/HealthWeightLog.php"
copy_if_exists "backend/app/Models/HealthStepLog.php"
copy_if_exists "backend/app/Models/HealthLabTest.php"
copy_if_exists "backend/app/Models/HealthMedication.php"
copy_if_exists "backend/app/Models/Project.php"
copy_if_exists "backend/app/Models/ProjectTask.php"
copy_if_exists "backend/app/Models/ProductivityTask.php"
copy_if_exists "backend/app/Models/ProductivityHabit.php"
copy_if_exists "backend/app/Models/ProductivityGoal.php"
copy_if_exists "backend/app/Models/ProductivityCalendarEvent.php"
copy_if_exists "backend/app/Models/AIRecommendation.php"

echo ""
echo "Exporting backend services..."
copy_if_exists "backend/app/Services/DashboardService.php"
copy_if_exists "backend/app/Services/FinanceDashboardService.php"
copy_if_exists "backend/app/Services/HealthDashboardService.php"
copy_if_exists "backend/app/Services/ProjectDashboardService.php"
copy_if_exists "backend/app/Services/ProductivityDashboardService.php"
copy_if_exists "backend/app/Services/AIRecommendationService.php"
copy_if_exists "backend/app/Services/AIRecommendationRuleEngineService.php"
copy_if_exists "backend/app/Services/AIRecommendationScoringService.php"

echo ""
echo "Exporting frontend router and layout..."
copy_if_exists "frontend/src/router/index.js"
copy_if_exists "frontend/src/router/index.ts"
copy_if_exists "frontend/src/layouts/AppLayout.vue"

echo ""
echo "Exporting frontend views..."
copy_if_exists "frontend/src/views/DashboardView.vue"
copy_if_exists "frontend/src/views/dashboard/DashboardView.vue"

copy_if_exists "frontend/src/views/finance/FinanceDashboardView.vue"
copy_if_exists "frontend/src/views/finance/FinanceAccountsView.vue"
copy_if_exists "frontend/src/views/finance/FinanceTransactionsView.vue"
copy_if_exists "frontend/src/views/finance/FinanceBudgetsView.vue"

copy_if_exists "frontend/src/views/health/HealthView.vue"
copy_if_exists "frontend/src/views/health/HealthNutritionView.vue"
copy_if_exists "frontend/src/views/health/HealthHydrationView.vue"
copy_if_exists "frontend/src/views/health/HealthWeightView.vue"
copy_if_exists "frontend/src/views/health/HealthStepsView.vue"
copy_if_exists "frontend/src/views/health/HealthLabTestsView.vue"
copy_if_exists "frontend/src/views/health/HealthMedicationsView.vue"

copy_if_exists "frontend/src/views/projects/ProjectsView.vue"
copy_if_exists "frontend/src/views/projects/ProjectDashboardView.vue"
copy_if_exists "frontend/src/views/projects/ProjectTasksView.vue"

copy_if_exists "frontend/src/views/productivity/ProductivityDashboardView.vue"
copy_if_exists "frontend/src/views/productivity/TasksView.vue"
copy_if_exists "frontend/src/views/productivity/HabitsView.vue"
copy_if_exists "frontend/src/views/productivity/GoalsView.vue"
copy_if_exists "frontend/src/views/productivity/CalendarView.vue"

copy_if_exists "frontend/src/views/ai/AIRecommendationsView.vue"
copy_if_exists "frontend/src/views/ai/AIRecommendationDashboardView.vue"

echo ""
echo "Exporting frontend services..."
copy_if_exists "frontend/src/services/api.js"
copy_if_exists "frontend/src/services/api.ts"
copy_if_exists "frontend/src/services/authService.js"
copy_if_exists "frontend/src/services/authService.ts"
copy_if_exists "frontend/src/services/dashboardService.js"
copy_if_exists "frontend/src/services/dashboardService.ts"
copy_if_exists "frontend/src/services/financeService.js"
copy_if_exists "frontend/src/services/financeService.ts"
copy_if_exists "frontend/src/services/healthService.js"
copy_if_exists "frontend/src/services/healthService.ts"
copy_if_exists "frontend/src/services/projectService.js"
copy_if_exists "frontend/src/services/projectService.ts"
copy_if_exists "frontend/src/services/productivityService.js"
copy_if_exists "frontend/src/services/productivityService.ts"
copy_if_exists "frontend/src/services/aiRecommendationService.js"
copy_if_exists "frontend/src/services/aiRecommendationService.ts"

echo ""
echo "Exporting frontend components..."
copy_if_exists "frontend/src/components"
copy_if_exists "frontend/src/components/common"
copy_if_exists "frontend/src/components/dashboard"
copy_if_exists "frontend/src/components/finance"
copy_if_exists "frontend/src/components/health"
copy_if_exists "frontend/src/components/projects"
copy_if_exists "frontend/src/components/productivity"
copy_if_exists "frontend/src/components/ai"

echo ""
echo "Exporting config files..."
copy_if_exists "frontend/package.json"
copy_if_exists "frontend/vite.config.js"
copy_if_exists "frontend/vite.config.ts"
copy_if_exists "backend/composer.json"
copy_if_exists "backend/.env.example"
copy_if_exists "docker-compose.yml"
copy_if_exists "docker-compose.prod.yml"

echo ""
echo "Creating archive..."
cd /tmp
tar -czf "${ARCHIVE_PATH}" "${EXPORT_NAME}"

echo ""
echo "=================================================="
echo " Export Completed Successfully"
echo " Archive Created:"
echo " ${ARCHIVE_PATH}"
echo "=================================================="
