<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\V1\NutritionFoodController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\V1\Dashboard\DashboardController;
use App\Http\Controllers\Api\LifeBalanceController;
// use App\Http\Controllers\Api\V1\Health\HealthMoodLogController;
use App\Http\Controllers\Api\FinanceAccountController;
use App\Http\Controllers\Api\FinanceTransactionController;
use App\Http\Controllers\Api\V1\Finance\FinanceBudgetController;
use App\Http\Controllers\Api\V1\Health\MedicationController;
use App\Http\Controllers\Api\V1\Health\SleepLogController;
use App\Http\Controllers\Api\V1\Health\HealthStepLogController;
use App\Http\Controllers\Api\V1\Health\HealthMoodLogController;
use App\Http\Controllers\Api\V1\HealthWeightLogController;
use App\Http\Controllers\Api\HealthNutritionLogController;
use App\Http\Controllers\Api\V1\HealthHydrationLogController;
use App\Http\Controllers\Api\V1\Health\HealthDashboardController;
use App\Http\Controllers\Api\V1\Health\HealthLabTestController;
/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Main API prefix generated by Laravel: /api
| Version prefix in this file: /v1
| Final API prefix: /api/v1
|
*/

/*
|--------------------------------------------------------------------------
| Public API Health Check
|--------------------------------------------------------------------------
*/

Route::get('/health', function () {
    return response()->json([
        'success' => true,
        'message' => 'Nix Life OS API is running.',
        'timestamp' => now()->toISOString(),
    ]);
});

/*
|--------------------------------------------------------------------------
| API Version 1
|--------------------------------------------------------------------------
*/

Route::prefix('v1')->group(function () {

    /*
    |--------------------------------------------------------------------------
    | Public Route Loading Test
    |--------------------------------------------------------------------------
    */

    Route::get('/sleep-route-test', function () {
        return response()->json([
            'success' => true,
            'message' => 'API v1 route file is loading correctly.',
        ]);
    });

    /*
    |--------------------------------------------------------------------------
    | Public Auth Routes
    |--------------------------------------------------------------------------
    */

    Route::prefix('auth')->group(function () {
        Route::post('/login', [AuthController::class, 'login']);
        Route::post('/register', [AuthController::class, 'register']);

        Route::middleware('auth:sanctum')->group(function () {
            Route::get('/me', [AuthController::class, 'me']);
            Route::post('/logout', [AuthController::class, 'logout']);
        });
    });

    /*
    |--------------------------------------------------------------------------
    | Protected Routes
    |--------------------------------------------------------------------------
    */

    Route::middleware('auth:sanctum')->group(function () {
        Route::prefix('nutrition')->group(function () {
            Route::get('/categories', [NutritionFoodController::class, 'categories']);

            Route::get('/foods/search', [NutritionFoodController::class, 'search']);
            Route::get('/foods/{id}/servings', [NutritionFoodController::class, 'servings']);
            Route::get('/foods/{id}', [NutritionFoodController::class, 'show']);
            Route::get('/foods', [NutritionFoodController::class, 'index']);
            Route::post('/foods/autofill', [NutritionFoodController::class, 'autofill']);



        });
        /*
        |--------------------------------------------------------------------------
        | Authenticated User
        |--------------------------------------------------------------------------
        */

        Route::get('/user', function (Request $request) {
            return response()->json([
                'success' => true,
                'message' => 'Authenticated user loaded successfully.',
                'data' => $request->user(),
            ]);
        });

        /*
        |--------------------------------------------------------------------------
        | Dashboard
        |--------------------------------------------------------------------------
        */

        Route::get('/dashboard/summary', [DashboardController::class, 'summary']);

        /*
        |--------------------------------------------------------------------------
        | Life Balance
        |--------------------------------------------------------------------------
        */

        Route::get('/life-balance/summary', [LifeBalanceController::class, 'summary']);

        /*
        |--------------------------------------------------------------------------
        | Finance Module
        |--------------------------------------------------------------------------
        */

        Route::prefix('finance')->group(function () {
            Route::get('/accounts', [FinanceAccountController::class, 'index']);
            Route::post('/accounts', [FinanceAccountController::class, 'store']);
            Route::get('/accounts/{id}', [FinanceAccountController::class, 'show']);
            Route::put('/accounts/{id}', [FinanceAccountController::class, 'update']);
            Route::patch('/accounts/{id}', [FinanceAccountController::class, 'update']);
            Route::delete('/accounts/{id}', [FinanceAccountController::class, 'destroy']);

            Route::get('/transactions', [FinanceTransactionController::class, 'index']);
            Route::post('/transactions', [FinanceTransactionController::class, 'store']);
            Route::get('/transactions/{id}', [FinanceTransactionController::class, 'show']);
            Route::put('/transactions/{id}', [FinanceTransactionController::class, 'update']);
            Route::patch('/transactions/{id}', [FinanceTransactionController::class, 'update']);
            Route::delete('/transactions/{id}', [FinanceTransactionController::class, 'destroy']);

            Route::get('/budgets', [FinanceBudgetController::class, 'index']);
            Route::post('/budgets', [FinanceBudgetController::class, 'store']);
            Route::get('/budgets/{id}', [FinanceBudgetController::class, 'show']);
            Route::put('/budgets/{id}', [FinanceBudgetController::class, 'update']);
            Route::patch('/budgets/{id}', [FinanceBudgetController::class, 'update']);
            Route::delete('/budgets/{id}', [FinanceBudgetController::class, 'destroy']);
        });

        /*
        |--------------------------------------------------------------------------
        | Health Module
        |--------------------------------------------------------------------------
        */
        Route::apiResource('health/medications', MedicationController::class);

        Route::prefix('health')->group(function () {
            Route::get('/dashboard', [HealthDashboardController::class, 'summary']);
            // Route::apiResource('lab-tests', HealthLabTestController::class);
            Route::get('/lab-tests', [HealthLabTestController::class, 'index']);
            Route::post('/lab-tests', [HealthLabTestController::class, 'store']);
            Route::get('/lab-tests/{id}', [HealthLabTestController::class, 'show']);
            Route::put('/lab-tests/{id}', [HealthLabTestController::class, 'update']);
            Route::patch('/lab-tests/{id}', [HealthLabTestController::class, 'update']);
            Route::delete('/lab-tests/{id}', [HealthLabTestController::class, 'destroy']);
            Route::get('/mood', [HealthMoodLogController::class, 'index']);
            Route::post('/mood', [HealthMoodLogController::class, 'store']);
            Route::get('/mood/{id}', [HealthMoodLogController::class, 'show']);
            Route::put('/mood/{id}', [HealthMoodLogController::class, 'update']);
            Route::patch('/mood/{id}', [HealthMoodLogController::class, 'update']);
            Route::delete('/mood/{id}', [HealthMoodLogController::class, 'destroy']);
                        /*
            |--------------------------------------------------------------------------
            | Sleep Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/sleep', [SleepLogController::class, 'index']);
            Route::post('/sleep', [SleepLogController::class, 'store']);
            Route::get('/sleep/{id}', [SleepLogController::class, 'show']);
            Route::put('/sleep/{id}', [SleepLogController::class, 'update']);
            Route::patch('/sleep/{id}', [SleepLogController::class, 'update']);
            Route::delete('/sleep/{id}', [SleepLogController::class, 'destroy']);

            Route::get('/sleep-test', function () {
                return response()->json([
                    'success' => true,
                    'message' => 'Sleep test route works.',
                ]);
            });

            /*
            |--------------------------------------------------------------------------
            | Steps Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/steps', [HealthStepLogController::class, 'index']);
            Route::post('/steps', [HealthStepLogController::class, 'store']);
            Route::get('/steps/{id}', [HealthStepLogController::class, 'show']);
            Route::put('/steps/{id}', [HealthStepLogController::class, 'update']);
            Route::patch('/steps/{id}', [HealthStepLogController::class, 'update']);
            Route::delete('/steps/{id}', [HealthStepLogController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Weight Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/weight', [HealthWeightLogController::class, 'index']);
            Route::post('/weight', [HealthWeightLogController::class, 'store']);
            Route::get('/weight/{id}', [HealthWeightLogController::class, 'show']);
            Route::put('/weight/{id}', [HealthWeightLogController::class, 'update']);
            Route::patch('/weight/{id}', [HealthWeightLogController::class, 'update']);
            Route::delete('/weight/{id}', [HealthWeightLogController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Nutrition Tracking
            |--------------------------------------------------------------------------
            */

            Route::get('/nutrition/summary', [HealthNutritionLogController::class, 'summary']);
            Route::get('/nutrition', [HealthNutritionLogController::class, 'index']);
            Route::post('/nutrition', [HealthNutritionLogController::class, 'store']);
            Route::get('/nutrition/{id}', [HealthNutritionLogController::class, 'show']);
            Route::put('/nutrition/{id}', [HealthNutritionLogController::class, 'update']);
            Route::patch('/nutrition/{id}', [HealthNutritionLogController::class, 'update']);
            Route::delete('/nutrition/{id}', [HealthNutritionLogController::class, 'destroy']);

            /*
            |--------------------------------------------------------------------------
            | Hydration Tracking
            |--------------------------------------------------------------------------
            */

            // Route::get('/mood', [HealthMoodLogController::class, 'index']);
            // Route::post('/mood', [HealthMoodLogController::class, 'store']);
            // Route::get('/mood/{id}', [HealthMoodLogController::class, 'show']);
            // Route::put('/mood/{id}', [HealthMoodLogController::class, 'update']);
            // Route::patch('/mood/{id}', [HealthMoodLogController::class, 'update']);
            // Route::delete('/mood/{id}', [HealthMoodLogController::class, 'destroy']);

            Route::get('/hydration', [HealthHydrationLogController::class, 'index']);
            Route::post('/hydration', [HealthHydrationLogController::class, 'store']);
            Route::get('/hydration/{id}', [HealthHydrationLogController::class, 'show']);
            Route::put('/hydration/{id}', [HealthHydrationLogController::class, 'update']);
            Route::patch('/hydration/{id}', [HealthHydrationLogController::class, 'update']);
            Route::delete('/hydration/{id}', [HealthHydrationLogController::class, 'destroy']);
        });

        /*
        |--------------------------------------------------------------------------
        | Projects Module
        |--------------------------------------------------------------------------
        |
        | Temporarily disabled because project controllers are missing.
        |
        */

        /*
        Route::prefix('projects')->group(function () {
            Route::get('/dashboard', [ProjectDashboardController::class, 'summary']);
            Route::get('/tasks', [ProjectTaskController::class, 'index']);
            Route::post('/tasks', [ProjectTaskController::class, 'store']);
            Route::get('/tasks/{id}', [ProjectTaskController::class, 'show']);
            Route::put('/tasks/{id}', [ProjectTaskController::class, 'update']);
            Route::patch('/tasks/{id}', [ProjectTaskController::class, 'update']);
            Route::delete('/tasks/{id}', [ProjectTaskController::class, 'destroy']);
        });
        */

        /*
        |--------------------------------------------------------------------------
        | Notifications Module
        |--------------------------------------------------------------------------
        |
        | Temporarily disabled because NotificationController does not exist.
        |
        */

        /*
        Route::prefix('notifications')->group(function () {
            Route::get('/', [NotificationController::class, 'index']);
            Route::post('/', [NotificationController::class, 'store']);
            Route::patch('/read-all', [NotificationController::class, 'markAllAsRead']);
            Route::get('/{id}', [NotificationController::class, 'show']);
            Route::patch('/{id}/read', [NotificationController::class, 'markAsRead']);
            Route::delete('/{id}', [NotificationController::class, 'destroy']);
        });

        Route::prefix('notification-settings')->group(function () {
            Route::get('/', [NotificationSettingController::class, 'index']);
            Route::put('/', [NotificationSettingController::class, 'update']);
            Route::patch('/', [NotificationSettingController::class, 'update']);
        });
        */

        /*
        |--------------------------------------------------------------------------
        | Monitoring Module
        |--------------------------------------------------------------------------
        |
        | Temporarily disabled because MonitoringController may not exist.
        |
        */

        /*
        Route::prefix('monitoring')->group(function () {
            Route::get('/summary', [MonitoringController::class, 'summary']);
            Route::get('/logs', [MonitoringController::class, 'logs']);
            Route::get('/errors', [MonitoringController::class, 'errors']);
            Route::get('/audit-logs', [MonitoringController::class, 'auditLogs']);
        });
        */
    });
});